# Generated by Django 4.2.1 on 2023-05-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('owner', models.IntegerField()),
                ('title', models.CharField(max_length=25)),
                ('text', models.CharField(max_length=250)),
            ],
        ),
    ]
